--DROP TABLE IF EXISTS BUMON_TBL;
--CREATE TABLE BUMON_TBL(
--	BUMON_CD CHAR(3),
--	BUMON_NM VARCHAR2(20),
--	PRIMARY KEY(BUMON_CD)
--);

DROP TABLE IF EXISTS PETS_TBL;
CREATE TABLE PETS_TBL(
	PET_ID INT AUTO_INCREMENT PRIMARY KEY,
	PET_NAME VARCHAR(30),
	PET_IMAGE VARCHAR(255)
);
