DROP TABLE IF EXISTS SIZE_TBL;
CREATE TABLE SIZE_TBL(
	SIZE_ID CHAR(3),
	SIZE_NAME VARCHAR2(5),
	PRIMARY KEY(SIZE_ID)
	);
	
DROP TABLE IF EXISTS REGISTER_TBL;
CREATE TABLE REGISTER_TBL(
    PET_ID INT,
    BIRTHDAY DATE,
    BREED_ID CHAR(3),
    GENDER VARCHAR(10),
    MEMO VARCHAR(255),
    PET_IMAGE VARCHAR(255),
    PET_NAME VARCHAR(50),
    PET_PASS VARCHAR(50),
    PRIMARY KEY(PET_ID)
);